---
name: Build and Push Node.js Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: proyecto-lealtad-purificadora-backend
      PROJECT_ID: carlosanguiano-369108
      GCE_INSTANCE: vm
      GCE_INSTANCE_ZONE: us-central1-a
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/us.gcr.io/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/us.gcr.io/$IMAGE_NAME:$GIT_TAG
        docker push us-docker.pkg.dev/$PROJECT_ID/us.gcr.io/$IMAGE_NAME:latest
        docker push us-docker.pkg.dev/$PROJECT_ID/us.gcr.io/$IMAGE_NAME:$GIT_TAG

    - name: Deploy image to GCE
      run: |-
        gcloud compute ssh vm  --command="gcloud auth activate-service-account github-actions@carlosanguiano-369108.iam.gserviceaccount.com --key-file=/home/runner/credentials.json && gcloud auth configure-docker && docker pull gcr.io/$PROJECT_ID/$IMAGE_NAME:latest && docker stop $IMAGE_NAME && docker remove $IMAGE_NAME && docker run -d --name $IMAGE_NAME -p 1337:1337 gcr.io/$PROJECT_ID/$IMAGE_NAME:latest && docker update --restart unless-stopped $IMAGE_NAME" --zone "us-central1-a"

    - name: Purge GCR images
      run: |-
        gcloud container images list-tags gcr.io/$PROJECT_ID/$IMAGE_NAME \
          --format="get(digest)" --filter="NOT tags=latest" | \
          awk -v image_path="gcr.io/$PROJECT_ID/$IMAGE_NAME@" '{print image_path $1}' | \
          xargs -r gcloud container images delete --force-delete-tags --quiet
